name: github_graph
description: GitHub Graphs a pure flutter widgets
version: 1.0.0
repository: 'https://github.com/Matt-Gleich/import_sorter'
homepage: 'https://mattglei.ch/#/'
maintainer: Matthew Gleich (@Matt-Gleich)

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  github_contributions: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^3.0.6
flutter:

import_sorter:
  emojis: true
